<?php
/**
 * Plugin Name: GatewayKit – Simple Payment Form, Donation & Checkout
 * Plugin URI:  https://pourmirzai.com/gatewaykit
 * Description: Accept payments and donations with 9 free gateways (Stripe, PayPal, Crypto). Fast checkout forms with zero platform fees and no WooCommerce bloat.
 * Version:     1.5.2
 * Author:      Morteza Pourmirzai
 * Author URI:  https://pourmirzai.com
 * Text Domain: gatewaykit
 * Domain Path: /languages
 * License:     GPL v2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Requires at least: 6.2
 * Requires PHP: 7.4
 * Plugin Slug: gatewaykit
 */

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Lite build identity.
if ( ! defined( 'GATEWAYKIT_LITE_VERSION' ) ) {
	define( 'GATEWAYKIT_LITE_VERSION', '1.5.2' );
}

/*
 |------------------------------------------------------------------------------------------------------------------------------------------
 | Freemius SDK (parent product — GatewayKit)
 |------------------------------------------------------------------------------------------------------------------------------------------
 | The Freemius SDK is loaded via Composer (vendor/freemius/wordpress-sdk) and
 | is shipped inside the Lite ZIP so it works on sites without Composer. The
 | autoloader must be required BEFORE the snippet so fs_dynamic_init() is
 | available. The snippet below was generated by the Freemius dashboard for the
 | "GatewayKit" parent product (id 34906, slug 'gatewaykit'); the menu slug
 | matches the real GatewayKit admin menu (src/Core/class-plugin.php:326).
 |
 | `has_addons => true` triggers the native "Add-Ons" submenu where users can
 | purchase/activate the GatewayKit Pro add-on. `has_paid_plans => false` keeps
 | the parent forever free — all monetization flows through the add-on.
 */
// Load the Composer autoloader for the bundled Freemius SDK.
//
// IMPORTANT (ERR-023): this MUST be guarded by a sentinel constant. The
// GatewayKit Pro add-on ships its own byte-identical vendor/ (same committed
// composer.lock), so its vendor/composer/autoload_real.php declares the SAME
// `ComposerAutoloaderInit<hash>` class. `require_once` only dedupes by file
// path, and Lite (`gatewaykit/vendor/autoload.php`) vs Pro
// (`gatewaykit-pro/vendor/autoload.php`) are different paths — without the
// sentinel, whichever plugin loads second fatals with
// "Cannot declare class ComposerAutoloaderInit...". The sentinel is
// load-order independent: the first of Lite/Pro to run loads the autoloader
// and sets the constant; the other skips it (the Freemius classes are already
// registered on spl_autoload). Because composer.lock is committed, the SDK is
// guaranteed byte-identical between the two ZIPs.
if ( file_exists( __DIR__ . '/vendor/autoload.php' ) && ! defined( 'GATEWAYKIT_FREEMIUS_AUTOLOADED' ) ) {
	require_once __DIR__ . '/vendor/autoload.php';
	define( 'GATEWAYKIT_FREEMIUS_AUTOLOADED', true );
}

if ( ! function_exists( 'gatewaykit_fs' ) ) {
	// Create a helper function for easy SDK access.
	function gatewaykit_fs() {
		global $gatewaykit_fs;

		if ( ! isset( $gatewaykit_fs ) ) {
			// Include Freemius SDK.
			// SDK is auto-loaded through Composer

			$gatewaykit_fs = fs_dynamic_init( array(
				'id'                  => '34906',
				'slug'                => 'gatewaykit',
				'premium_slug'        => 'gatewaykit-lite-premium',
				'type'                => 'plugin',
				'public_key'          => 'pk_61e3343a3d4d3f394bc2f4e3ea0b1',
				'is_premium'          => false,
				'has_addons'          => true,
				'has_paid_plans'      => false,
				'is_org_compliant'    => true,
				'menu'                => array(
					'slug'           => 'gatewaykit',
					'support'        => false,
				),
			) );
		}

		return $gatewaykit_fs;
	}

	// Init Freemius.
	gatewaykit_fs();
	// Signal that SDK was initiated.
	do_action( 'gatewaykit_fs_loaded' );
}

/*
 |------------------------------------------------------------------------------------------------------------------------------------------
 | Uninstall cleanup (Freemius `after_uninstall`)
 |------------------------------------------------------------------------------------------------------------------------------------------
 | WordPress only fires ONE uninstall handler per plugin: if `uninstall.php`
 | exists it runs INSTEAD of registered `register_uninstall_hook()` callbacks,
 | which means Freemius's uninstall-tracking hook never runs and we lose churn
 | analytics. To let Freemius report the uninstall event to its server AND run
 | our cleanup afterward, we delete `uninstall.php` and register the cleanup
 | function on Freemius's `after_uninstall` action (see ARCH-021). The cleanup
 | logic is identical to the old `uninstall.php` and remains opt-in via the
 | `gatewaykit_delete_data_on_uninstall` option.
 */
if ( ! function_exists( 'gatewaykit_lite_uninstall_cleanup' ) ) {
	/**
	 * Complete opt-in cleanup of all GatewayKit data on uninstall.
	 *
	 * Runs only when an administrator has explicitly enabled it beforehand via
	 * the "Remove all GatewayKit data on deletion" setting (option
	 * `gatewaykit_delete_data_on_uninstall`). When the option is absent or false,
	 * all data is preserved so users can reinstall without losing transactions.
	 *
	 * @return void
	 */
	function gatewaykit_lite_uninstall_cleanup() {
		if ( get_option( 'gatewaykit_delete_data_on_uninstall' ) !== '1' ) {
			return;
		}

		global $wpdb;

		// 1. Drop custom database tables.
		$gatewaykit_tables = array(
			$wpdb->prefix . 'gatewaykit_payment_transactions',
			$wpdb->prefix . 'gatewaykit_payment_logs',
			$wpdb->prefix . 'gatewaykit_discounts',
			$wpdb->prefix . 'gatewaykit_discount_usage',
			$wpdb->prefix . 'gatewaykit_transaction_notes',
		);

		foreach ( $gatewaykit_tables as $gatewaykit_table ) {
			$wpdb->query( $wpdb->prepare( 'DROP TABLE IF EXISTS %i', $gatewaykit_table ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.SchemaChange, WordPress.DB.DirectDatabaseQuery.NoTruncation, WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		}

		// 1b. Delete sample forms and receipt page if created.
		$receipt_page_id = (int) get_option( 'gatewaykit_receipt_page_id', 0 );
		if ( $receipt_page_id ) {
			wp_delete_post( $receipt_page_id, true );
		}
		$default_form_ids = (array) get_option( 'gatewaykit_default_form_ids', array() );
		foreach ( $default_form_ids as $form_id ) {
			if ( $form_id ) {
				wp_delete_post( (int) $form_id, true );
			}
		}

		// 2. Delete all gatewaykit_* options.
		$gatewaykit_option_names = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$wpdb->prepare(
				'SELECT option_name FROM %i WHERE option_name LIKE %s',
				$wpdb->options,
				$wpdb->esc_like( 'gatewaykit_' ) . '%'
			)
		);

		if ( ! empty( $gatewaykit_option_names ) ) {
			foreach ( $gatewaykit_option_names as $gatewaykit_option_name ) {
				delete_option( $gatewaykit_option_name );
			}
		}

		// 3. Delete all gatewaykit_* transients (stored in options with/without prefix).
		$gatewaykit_transient_names = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$wpdb->prepare(
				'SELECT option_name FROM %i WHERE option_name LIKE %s OR option_name LIKE %s',
				$wpdb->options,
				$wpdb->esc_like( '_transient_gatewaykit_' ) . '%',
				$wpdb->esc_like( '_transient_timeout_gatewaykit_' ) . '%'
			)
		);

		if ( ! empty( $gatewaykit_transient_names ) ) {
			foreach ( $gatewaykit_transient_names as $gatewaykit_transient_option ) {
				delete_option( $gatewaykit_transient_option );
			}
		}

		// 4. Clear any scheduled cron events registered by the plugin.
		$gatewaykit_cron = get_option( 'cron', array() );
		if ( is_array( $gatewaykit_cron ) ) {
			foreach ( $gatewaykit_cron as $gatewaykit_timestamp => $gatewaykit_hooks ) {
				if ( ! is_array( $gatewaykit_hooks ) ) {
					continue;
				}
				foreach ( array_keys( $gatewaykit_hooks ) as $gatewaykit_hook ) {
					if ( 0 === strpos( $gatewaykit_hook, 'gatewaykit_' ) ) {
						wp_clear_scheduled_hook( $gatewaykit_hook );
					}
				}
			}
		}
	}
}

// Register cleanup with Freemius so uninstall events are tracked on the
// dashboard AND the cleanup runs AFTER Freemius has reported the uninstall.
if ( function_exists( 'gatewaykit_fs' ) ) {
	gatewaykit_fs()->add_action( 'after_uninstall', 'gatewaykit_lite_uninstall_cleanup' );
}

// === BOOT === (everything below is identical across all builds)

// Core plugin constants.
if ( ! defined( 'GATEWAYKIT_VERSION' ) ) {
	define( 'GATEWAYKIT_VERSION', GATEWAYKIT_LITE_VERSION );
}
define( 'GATEWAYKIT_PLUGIN_FILE', __FILE__ );
define( 'GATEWAYKIT_PLUGIN_DIR', plugin_dir_path( __FILE__ ) );
define( 'GATEWAYKIT_PLUGIN_URL', plugin_dir_url( __FILE__ ) );
define( 'GATEWAYKIT_PLUGIN_BASENAME', plugin_basename( __FILE__ ) );

/*
|------------------------------------------------------------------------------------------------------------------------------------------
| Pro license detection helpers (Lite-side)
|------------------------------------------------------------------------------------------------------------------------------------------
| The real license gate lives in `gatewaykit_pro_is_licensed()` inside the
| Pro add-on (gatewaykit-pro.php), but that function only exists AFTER the
| Pro add-on is loaded. Lite Core needs a safe way to detect a licensed Pro
| install so it can show Pro-only features (e.g. CSV export) as locked /
| unlocked on the shared admin pages. These wrappers are guarded by
| `function_exists()` so they are no-ops when Pro is not installed.
|
| See ARCH-022: Pro must NEVER add its own submenu — it enhances the shared
| Lite admin pages instead.
|
| NOTE: these helpers live in the SHARED BOOT section so they ship in BOTH
| dev (repo-root gatewaykit.php) and the composed Lite entry file produced
| by `php bin/build.php lite`. Pro (entry_source=gatewaykit-pro.php) skips
| composition entirely, so it never re-declares these — Pro keeps its own
| `gatewaykit_pro_is_licensed()` instead.
 */
if ( ! function_exists( 'gatewaykit_is_pro_licensed' ) ) {
	/**
	 * Detect whether GatewayKit Pro is installed AND has a valid paying license.
	 *
	 * @return bool
	 */
	function gatewaykit_is_pro_licensed() {
		return function_exists( 'gatewaykit_pro_is_licensed' )
			&& gatewaykit_pro_is_licensed();
	}
}

if ( ! function_exists( 'gatewaykit_get_upgrade_url' ) ) {
	/**
	 * Return the best available upgrade URL for sending Lite users to Pro checkout.
	 *
	 * Preference order:
	 *  1. The Pro add-on SDK's native upgrade URL (most accurate — deep-links
	 *     into the Pro checkout with the current install's billing context).
	 *  2. The parent Freemius SDK's Add-Ons page (used when the Pro add-on
	 *     is not yet installed — this is the typical Lite-only user state).
	 *  3. The public marketing site as a hard fallback.
	 *
	 * @return string
	 */
	function gatewaykit_get_upgrade_url() {
		if ( function_exists( 'gatewaykit_pro_fs' ) ) {
			return gatewaykit_pro_fs()->get_upgrade_url();
		}
		if ( function_exists( 'gatewaykit_fs' ) ) {
			return gatewaykit_fs()->get_addons_url();
		}
		return 'https://pourmirzai.com/gatewaykit/';
	}
}

if ( ! function_exists( 'gatewaykit_fputcsv' ) ) {
	/**
	 * Write an array row as CSV to an open file pointer.
	 *
	 * Lightweight wrapper around PHP's fputcsv(). All GatewayKit CSV exports
	 * (transactions, logs) funnel through this helper so encoding and
	 * delimiter behavior stays consistent in one place.
	 *
	 * @param resource $handle Open file pointer.
	 * @param array    $fields Row values.
	 * @return int|false Bytes written, or false on failure.
	 */
	function gatewaykit_fputcsv( $handle, array $fields ) {
		// Mitigate CSV formula injection: prefix cells starting with
		// dangerous characters with a single quote so spreadsheet
		// applications treat them as text, not formulas.
		$fields = array_map(
			function ( $value ) {
				if ( is_string( $value ) && '' !== $value ) {
						$first = $value[0];
					if ( false !== strpos( "=+-@\t\r", $first ) ) {
						$value = "'" . $value;
					}
				}
				return $value;
			},
			$fields
		);

		return fputcsv( $handle, $fields );
	}
}

// Boot the Core autoloader (resolves Core/Utils/Admin/Elementor classes).
require_once GATEWAYKIT_PLUGIN_DIR . 'src/Core/class-autoloader.php';

// Boot the plugin controller. Gateways and features are discovered
// automatically from src/Gateways/* and src/Features/* via module.php.
require_once GATEWAYKIT_PLUGIN_DIR . 'src/Core/class-plugin.php';

GatewayKit::get_instance();
